package com.exception;

public class ExceptionTest2 {
	public void first(int num) throws Exception {
		second(num);
	}
	public void second(int num) throws Exception {
		third(num);
	}
	public void third(int num) throws Exception {
		if(num > 0) {
			System.out.println(++num);
		}else {
			throw new Exception();
		}
	}
	
	public static void main(String[] args) throws Exception {
		new ExceptionTest2().first(-1);
		
	}

}
