package com.exception;

public class ExceptionTest2 {
	public void first(int num) {
		second(num);
	}
	public void second(int num) {
		third(num);
	}
	public void third(int num) {}
	
	public static void main(String[] args) {
		new ExceptionTest2().first(1);

	}

}
