package com.exception;


public class ArrayTest {
	public static void main(String[] args) {
		int data[] = {10,20,30};
		
		for (int i = 0; i <= data.length; i++) {
			try {
				System.out.println(data[i]);
			}catch(){
				
			}
			
		}
		
		System.out.println("done...");
	}
}
